version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            mkdir /tmp/terraform
            pushd /tmp/terraform
            wget -c https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            unzip terraform_0.12.24_linux_amd64.zip
            popd
      - run:
          name: Check terraform state path
          command: |
            pushd infrastructure
            ./checkStatePath.sh
            popd
      - run:
          name: Apply terraform
          command: |
            pushd infrastructure/active
            /tmp/terraform/terraform init
            /tmp/terraform/terraform apply --auto-approve -lock=true -lock-timeout=300s
            /tmp/terraform/terraform output -json > /tmp/terraform.output.json
            /tmp/terraform/terraform output > /tmp/terraform.output
            popd
      - run:
          name: Configure Zeit
          command: |
            sudo npm install -g now
            mkdir .now
            echo "{\"projectId\":\"$ZEIT_PROJECT\",\"orgId\":\"$ZEIT_ORG\"}" > ./.now/project.json
      - run:
          name: Deploy Website
          command: |
            pushd website
            cp /tmp/terraform.output.json ./infrastructure.json
            now --prod -t $ZEIT_TOKEN
            popd
  test:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo hello
  delete:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            mkdir /tmp/terraform
            pushd /tmp/terraform
            wget -c https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            unzip terraform_0.12.24_linux_amd64.zip
            popd
      - run:
          name: Delete infrastructure
          command: |
            pushd infrastructure/dormant
            /tmp/terraform/terraform init
            /tmp/terraform/terraform apply --auto-approve
            popd

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - delete
