version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            mkdir /tmp/terraform
            pushd /tmp/terraform
            wget -c https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip
            unzip terraform_0.12.23_linux_amd64.zip
            popd
      - run:
          name: Check terraform state path
          command: |
            pushd infrastructure
            ./checkStatePath.sh
            popd
      - run:
          name: Apply terraform
          command: |
            pushd infrastructure/active
            /tmp/terraform/terraform init
            /tmp/terraform/terraform apply --auto-approve -lock=true -lock-timeout=300s -var-file=../../website/project.tfvars.json
            /tmp/terraform/terraform output -json > /tmp/terraform.output.json
            /tmp/terraform/terraform output > /tmp/terraform.output
            popd
      - run:
          name: Deploy Website
          command: |
            echo "That activity has been delegated to https://zeit.co/ferdegje"
  test:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo hello
  delete:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            mkdir /tmp/terraform
            pushd /tmp/terraform
            wget -c https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip
            unzip terraform_0.12.23_linux_amd64.zip
            popd
      - run:
          name: Delete infrastructure
          command: |
            pushd infrastructure/dormant
            /tmp/terraform/terraform init
            /tmp/terraform/terraform apply --auto-approve -var-file=../../website/project.tfvars.json
            popd

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - delete
