/*
 * action types
 */
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const VALIDATE_USER = 'VALIDATE_USER'
export const VALIDATE_USER_SUCCESS = 'VALIDATE_USER_SUCCESS'